### ISSUE TITLE
Load private/public keys from environment variables

### ISSUE THREAD

**Issue by andyzickler** [chameleonbr/node-red-contrib-jwt#2]
We keep our secrets in environment variables. It would be useful to set `NODE_RED_NODE_JWT_PUBLIC_KEY` and `NODE_RED_NODE_JWT_PRIVATE_KEY` and use those if they're set.

**Comment by ram1505** [comment]
Hi,
In my flow, I've a dynamical client_secret which is required to sign the JWT. Therefore, I cannot store the client_secret on my environmental variable. Is there a workaround where I don't have to manually key in the client_secret under the "secret" text box of the node?

**Comment by ram1505** [comment]
Actually, I've the client_secret in my global variable. How can I use this global variable with the JWT_SIGN node? I'm using a pre-shared key and therefore my payload will have a client_secret which is then stored in a global variable. When I use the JWT_SIGN node, with HS256, it asks me to enter either a "secret" property on the node text input field or use an environmental variable NODE_RED_NODE_JWT_SECRET. Please help. Can I somehow use my global variable without having to enter the secret each time on the property of the node?
